version: "3.5"

services:
  db:
    image: mysql:5.7
    volumes:
      - humble_blog:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}

  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:${APP_HOST}
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  backend:
    image: node:12
    working_dir: /app
    restart: always
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    command:
      - /bin/bash
      - -c
      - yarn && yarn start
    env_file: .env

volumes:
  humble_blog:
